### ISSUE TITLE
Github Release action for v2.2.0 failed

### ISSUE THREAD

**Issue by bpepple** [lemonsaurus/django-simple-bulma#70]
Looks like your Github action is using the depreciated legacy method. I believe if you update to a more recent gh action (like pypa/gh-action-pypi-publish@v1.4.1) it should work.

**Comment by lemonsaurus** [comment]
cool. I did notice it failed, just haven't had time to examine it yet. will take a look soon.

**Comment by bpepple** [comment]
No worries.

**Comment by lemonsaurus** [comment]
seems like this was just a bad token from the migration of this repo to my personal github. works now.

however, I still think it's worth upgrading that deprecated action, so I'll keep this issue open.

**Comment by lemonsaurus** [comment]
Thanks for this suggestion, I've updated the action now and tested a release successfully.
