### ISSUE TITLE
Using multiple themes

### ISSUE THREAD

**Issue by GDWR** [lemonsaurus/django-simple-bulma#86]
Currently, I attempting to use this project's [multiple themes](https://github.com/lemonsaurus/django-simple-bulma#multiple-themes) functionality to create a dark and light mode. 

While trying to do this am I facing issues with sending duplicate `.js` files, as the tag has been used twice.
With this `.js` being served twice, it is creating two event handlers for the navbar burger menu on the page and is causing it to stop working.

**Django template:**
```django
{% bulma %}
{% bulma 'dark' %}
```
**Firefox network tab when loading the page:**
![image](https://user-images.githubusercontent.com/57012020/153653835-ed04f079-53c6-47f1-890e-6c8dd18ec7f0.png)

I am unsure how Django extensions work, but having a way to ensure that only one `.js` file is served would allow me to implement the functionality I want.

---
This functionality for switching themes could be implemented into this package also, as it would be a nice to have for other users of `django-simple-bulma`

**Comment by jchristgit** [comment]
I believe in https://github.com/lemonsaurus/django-simple-bulma/blob/main/django_simple_bulma/templatetags/django_simple_bulma.py#L39 a condition would need to be added for only optionally including the JS files?

**Comment by lemonsaurus** [comment]
Yes @jchristgit, that sounds totally fine. We could do that.
