### ISSUE TITLE
how to use django-allauth forms on bulma login page?

### ISSUE THREAD

**Issue by GaziAshiq** [lemonsaurus/django-simple-bulma#89]
I want to use bulma for my login page. I'm using django-allauth for authentication. So can I use form on login page as crispy form tag. how can I do that?

**Comment by lemonsaurus** [comment]
I'm afraid crispy forms won't work with this plugin. The HTML in crispy is very hard coded, so getting that working would basically require a whole other plugin.

in fact, I did start work on a django-crispy-bulma plugin, but that project never found feet and was abandoned.

to make your login page with this plugin, you'll have to build it without crispy.

**Comment by GaziAshiq** [comment]
Thanks for your concern. I was looking for a solution and found this now 'https://github.com/timonweb/django-bulma'. it's working

**Comment by lemonsaurus** [comment]
Nice! glad you found a solution, and thanks for the info!
